AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaRoleArn:
    Type: String
    NoEcho: true
  S3BucketName:
    Type: String
    NoEcho: true
  S3Key:
    Type: String
    NoEcho: true

Resources:
  PredictFunction:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      FunctionName: predict-api
      Runtime: nodejs24.x
      Handler: index.handler
      Role: !Ref LambdaRoleArn
      MemorySize: 128
      Timeout: 30
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3Key
