AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  EndpointName:
    Type: String
    NoEcho: true
  OriginSecret:
    Type: String
    NoEcho: true

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 128

Resources:
  PredictHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: sam-predict-api

    CorsConfiguration:
      AllowMethods:
        - POST
        - OPTIONS

      AllowHeaders:
        - Content-Type
        - x-api-key

      AllowOrigins:
        - "*"

  PredictFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam-predict-api

      CodeUri: src/

      Handler: index.handler

      Environment:
        Variables:
          ENDPOINT_NAME: !Ref EndpointName
          ORIGIN_SECRET: !Ref OriginSecret

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sagemaker:InvokeEndpoint
              Resource: "*"

      Events:
        PredictEndpoint:
          Type: HttpApi
          Properties:
            ApiId: !Ref PredictHttpApi
            Path: /api/predict
            Method: POST

Outputs:
  ApiUrl:
    Value: !Sub "https://${PredictHttpApi}.execute-api.${AWS::Region}.amazonaws.com/api/predict"